networks:
  web:
    external: true
    name: web
  internal:
    external: false

services:
  api:
    image: ghcr.io/jonathanpiaget/searchmark-api:production
    env_file:
      - .envs/.local/.postgres
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.fastapi.rule: "Host(`searchmark.${DOMAIN}`)"
      traefik.http.services.fastapi.loadbalancer.server.port: "80"
      traefik.http.routers.fastapi.tls.certresolver: "${CERT_RESOLVER}"
      traefik.http.routers.fastapi.entrypoints: "web-secure"
      traefik.http.routers.fastapi.tls: "true"
      traefik.docker.network: "web"
      traefik.http.routers.fastapi.middlewares: "csrf@file"
    networks:
      - internal
      - web
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    build:
      context: .
      dockerfile: compose/production/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .envs/.local/.postgres
    restart: unless-stopped
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  local_postgres_data:
  local_postgres_data_backups:
