services:
  api:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: searchmark_api_local_fastapi
    container_name: searchmark_api_local_fastapi
    ports:
      - "8000:80"
    env_file:
      - .envs/.local/.postgres
    volumes:
      - .:/app:z
      - /app/.venv
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    build:
      context: .
      dockerfile: compose/production/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - .envs/.local/.postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  local_postgres_data:
  local_postgres_data_backups:
