#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname "${0}")"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

if [[ -z ${1+x} ]]; then
    message_error "Backup filename is not specified. Usage: restore <backup_filename>"
    exit 1
fi

backup_filename="${BACKUP_DIR_PATH}/${1}"
if [[ ! -f "${backup_filename}" ]]; then
    message_error "Backup file '${backup_filename}' does not exist."
    exit 1
fi

export PGHOST="${POSTGRES_HOST:-localhost}"
export PGPORT="${POSTGRES_PORT:-5432}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

message_info "Restoring database from '${backup_filename}'..."

if [[ "${PGUSER}" == "postgres" ]]; then
    message_error "Restoring as 'postgres' user is not supported. Assign 'POSTGRES_USER' env with another user."
    exit 1
fi

message_info "Dropping existing database..."
dropdb "${PGDATABASE}"

message_info "Creating new database..."
createdb --owner="${PGUSER}"

message_info "Applying backup..."
gunzip -c "${backup_filename}" | psql

message_success "Database restored successfully from '${backup_filename}'."
