#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

working_dir="$(dirname "${0}")"
source "${working_dir}/_sourced/constants.sh"
source "${working_dir}/_sourced/messages.sh"

if [[ -z ${1+x} ]]; then
    message_error "Backup filename is not specified. Usage: rmbackup <backup_filename>"
    exit 1
fi

backup_filename="${BACKUP_DIR_PATH}/${1}"
if [[ ! -f "${backup_filename}" ]]; then
    message_error "Backup file '${backup_filename}' does not exist."
    exit 1
fi

message_info "Removing backup '${backup_filename}'..."

rm -f "${backup_filename}"

message_success "Backup '${backup_filename}' removed successfully."
